### PR TITLE
fix create datablock for physicsshapes.

### LINKED ISSUE #1689: Unable to create a physicsshape datablock from datablock editor.
Unable to create a physicsshape datablock from datablock editor.

```
<input> (0): preload failed for myTestPS: PhysicsShapeData::preload - No shape name defined..
tools/datablockEditor/datablockEditor.cs (716): Unable to find object: 'myTestPS' attempting to call function 'getId'
tools/datablockEditor/datablockEditor.cs (193): Unable to find object: '' attempting to call function 'getClassName'
tools/datablockEditor/datablockEditor.cs (201): Unable to find object: '' attempting to call function 'getId'
tools/datablockEditor/datablockEditor.cs (504): Unable to find object: '' attempting to call function 'getId'
Set::remove: Object "" does not exist in set
```

VS2015+Bullet+Windows7
tested in last commit 5fa8504568871e227c557a6a584f487b3bbce29f

### PR DESCRIPTION
**Pull request by John3**
fix #1689

This fix a bug when you try to create a new physics shape datablock.

### CODE REVIEW

File: Engine/source/T3D/physics/physicsShape.cpp [hunk 1]
```diff
@@ -271,6 +271,8 @@ bool PhysicsShapeData::preload( bool server, String &errorBuffer )
 {
    if ( !Parent::preload( server, errorBuffer ) )
       return false;
+   
+   if( server ) return true;
```
Comment (rextimmy) [inline Engine/source/T3D/physics/physicsShape.cpp]: This needs to be removed, it stops the TSShape and PhysicsCollisionRef from been created server side.

**Comment by John3** [comment]
thanks!

**Comment by Lopuska** [comment]
It's ok. :)
